package cn.kim.service;


import cn.kim.entity.CxfFileWrapper;
import cn.kim.entity.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-02-15T10:38:20.415+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://inf.service.file.cn/", name = "FileWS")
@XmlSeeAlso({ObjectFactory.class})
public interface FileWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.Download")
    @WebMethod
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.DownloadResponse")
    public CxfFileWrapper download(
            @WebParam(name = "file", targetNamespace = "")
                    CxfFileWrapper file
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "upload", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.Upload")
    @WebMethod
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.UploadResponse")
    public boolean upload(
            @WebParam(name = "file", targetNamespace = "")
                    CxfFileWrapper file
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.Delete")
    @WebMethod
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://inf.service.file.cn/", className = "cn.kim.entity.DeleteResponse")
    public boolean delete(
            @WebParam(name = "file", targetNamespace = "")
                    CxfFileWrapper file
    );
}
